In [18]:
from scipy import stats
import pandas as pd
import plotly.express as plt
import numpy as np
import os
import statsmodels.api as sm
from matplotlib import pyplot

In [19]:
property = os.path.join('property_sales.csv')
property_df = pd.read_csv(property)
property_df.head(15)

,OBJECTID,CRV,Sale_Date,InRTOStudy,Neighborhoood,Ward,PropType,Address,HouseNumber,HouseNum,...,SuffixDire,Grantee,Grantor,Adjusted_S,Gross_Sale,SaleDate,Downpayment,X,Y,PIN_TEXT
0,10001,204924.0,2014-02-26T00:00:00.000Z,No,VICTORY,4,Residential,4526 Xerxes AVE N,4526,NaN,...,N,David Anderson,Janet L Rollmann,155103,159900.0,2014-02-26T00:00:00.000Z,15990.0,516655.530538,190166.659712,1111821330128
1,10002,233969.0,2014-06-25T00:00:00.000Z,Yes,VICTORY,4,Residential,4566 Xerxes AVE N,4566,NaN,...,N,Darryl L Bell,Deborah J Boardley,162000,169500.0,2014-06-25T00:00:00.000Z,4448.0,516643.782209,190666.537525,1111821330138
2,10003,233969.0,2014-06-25T00:00:00.000Z,Yes,VICTORY,4,Residential,4566 Xerxes AVE N,4566,NaN,...,N,Darryl L Bell,Tracy Everson,162000,169500.0,2014-06-25T00:00:00.000Z,4448.0,516643.782209,190666.537525,1111821330138
3,10004,71027.0,2014-07-18T00:00:00.000Z,Yes,VICTORY,4,Residential,4574 Xerxes AVE N,4574,NaN,...,N,Krista M Torning,Karen L Holland,162500,162500.0,2014-07-18T00:00:00.000Z,NaN,516641.329215,190769.809892,1111821330140
4,10005,272354.0,2014-10-10T00:00:00.000Z,Yes,LINDEN HILLS,13,Residential,4600 Xerxes AVE S,4600,NaN,...,S,Robert W Nichols III,Brian D Renbarger,277900,284900.0,2014-10-10T00:00:00.000Z,2000.0,516598.558439,146839.634287,1702824210001
5,10006,203371.0,2014-02-18T00:00:00.000Z,Yes,LINDEN HILLS,13,Residential,4649 Xerxes AVE S,4649,NaN,...,S,John J Kelly,Brian T Schubring,397125,400000.0,2014-02-18T00:00:00.000Z,3000.0,516796.062107,146330.023267,1702824120100
6,10007,203371.0,2014-02-18T00:00:00.000Z,Yes,LINDEN HILLS,13,Residential,4649 Xerxes AVE S,4649,NaN,...,S,John J Kelly,Donald E Hartzell,397125,400000.0,2014-02-18T00:00:00.000Z,3000.0,516796.062107,146330.023267,1702824120100
7,10008,223492.0,2014-05-22T00:00:00.000Z,Yes,VICTORY,4,Residential,4718 Xerxes AVE N,4718,NaN,...,N,Ben G Stelmach,Nachiket Katti,167000,167000.0,2014-05-22T00:00:00.000Z,NaN,516634.683407,191076.266507,1111821320037
8,10009,221789.0,2014-05-15T00:00:00.000Z,No,VICTORY,4,Residential,4726 Xerxes AVE N,4726,NaN,...,N,Ryan Trippe,Fannie Mae,145900,148500.0,2014-05-15T00:00:00.000Z,7425.0,516632.626661,191175.998364,1111821320039
9,10010,NaN,2014-05-03T00:00:00.000Z,No,FULTON,13,Double Bungalow,4741 Xerxes AVE S,4741,NaN,...,S,Timothy M Blazek,Debra J Blazek,100,100.0,2014-05-03T00:00:00.000Z,NaN,516798.758162,145771.082702,1702824120130
10,10011,NaN,2014-05-03T00:00:00.000Z,No,FULTON,13,Double Bungalow,4741 Xerxes AVE S,4741,NaN,...,S,Timothy M Blazek,Timothy M Blazek,100,100.0,2014-05-03T00:00:00.000Z,NaN,516798.758162,145771.082702,1702824120130
11,10012,NaN,2014-05-03T00:00:00.000Z,No,FULTON,13,Double Bungalow,4741 Xerxes AVE S,4741,NaN,...,S,Timothy M Blazek,Timothy Blazek,100,100.0,2014-05-03T00:00:00.000Z,NaN,516798.758162,145771.082702,1702824120130
12,10013,287986.0,2014-11-18T00:00:00.000Z,Yes,FULTON,13,Residential,4841 Xerxes AVE S,4841,NaN,...,S,Daniel T Langseth,Torben Rytt,325000,333000.0,2014-11-18T00:00:00.000Z,3000.0,516798.984702,145115.986651,1702824130014
13,10014,216085.0,2014-04-24T00:00:00.000Z,No,FULTON,13,Residential,4908 Xerxes AVE S,4908,NaN,...,S,Leanna J Basile,Endres Custom Homes Inc,537283,537283.0,2014-04-24T00:00:00.000Z,53783.0,516610.369633,144765.012116,1702824240143
14,10015,216085.0,2014-04-24T00:00:00.000Z,No,FULTON,13,Residential,4908 Xerxes AVE S,4908,NaN,...,S,Erik O Hester,Endres Custom Homes Inc,537283,537283.0,2014-04-24T00:00:00.000Z,53783.0,516610.369633,144765.012116,1702824240143

In [31]:
population = property_df['Downpayment'].dropna()

In [28]:
y = property_df['Gross_Sale']

In [42]:
sample = np.random.choice(population, size=1000)

In [40]:
stats.ttest_1samp(sample, y.mean())

Ttest_1sampResult(statistic=-49.159555663945305, pvalue=6.155441784057254e-269)